apiVersion: apps/v1
kind: Deployment
metadata:
  name: configurable
  labels: 
    kubernetes.courselabs.co: configmaps
    app: configurable
spec:
  selector:
    matchLabels:
      app: configurable
  template:
    metadata:
      labels:
        app: configurable
        broken: bad-mount
    spec:
      containers:
        - name: app
          image: sixeyed/configurable:21.04
          volumeMounts:
            - name: config-override
              mountPath: "/app"
              readOnly: true
      volumes:
        - name: config-override
          configMap:
            name: configurable-override
            items:
              - key: override.json
                path: appsettings.json
