apiVersion: v1
kind: Service
metadata:
  name: whoami-zero-matches
  labels:
    kubernetes.courselabs.co: services
spec:
  selector:
    app: whoami
    version: v2  # no Pod has this label
  ports:
    - name: http
      port: 8010
      targetPort: 80