services:
  rng-api:
    image: courselabs/rng-api:21.05
    secrets:
      - source: dotnet-logging
        target: /app/config/logging.json
      - source: rng-api
        target: /app/config/override.json
    networks:
      - app-net

  rng-web:
    image: courselabs/rng-web:21.05
    secrets:
      - source: dotnet-logging
        target: /app/config/logging.json
      - source: rng-web
        target: /app/config/override.json
    networks:
      - app-net

networks:
  app-net:
