services:
  rng-api:
    ports:
      - "8189:80"

  rng-web:
    ports:
      - "8190:80"

secrets:
  dotnet-logging:
    file: ./config/dev/logging.json
  rng-api:
    file: ./config/dev/api/override.json
  rng-web:
    file: ./config/dev/web/override.json
