services:
  rng-api:
    image: courselabs/rng-api:21.05
    env_file: ./config/logging.env
    ports:
      - "8089:80"
    networks:
      - app-net

  rng-web:
    image: courselabs/rng-web:21.05
    env_file: ./config/logging.env
    environment:
      - RngApi__Url=http://rng-api/rng
    ports:
      - "8090:80"
    networks:
      - app-net

networks:
  app-net: