apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default
  labels:
    kubernetes.courselabs.co: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: Prefix
        backend:
          service:
            name: nginx-internal
            port: 
              name: http
  tls:
    - secretName: https-local